#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('Dating Bot', '1.0');

// اضافه کردن commandهای خودتان
// $app->add(new YourCommand());

$app->run();